jmcdo29/nest-commander

packages/nest-commander/src/command-runner-core.service.ts
pnpm-lock.yaml

Parse handlers had to define all data inside the `parseHandler`
method because `this` was not being properly bound to the class.
`this` is not properly bound to the handler and it works as expected.

fix: allow for option handlers to use `this`

---

README.md
packages/nest-commander/src/command.factory.ts

This forwards the second argument of `CommandRunner.run` to the `logger` option of `NestFactory.create`.
Note: I had to run all commits with `--no-verify` as I don't have pnpm installed. I did run `npm run format -- --check` though

Support logger arg

---

apps/docs/docs/features/commander.md

Following #38 I thought it would be nice to specify to users where they can read up on how `@Options` works. Hopefully it helps in preventing silly issues like mine :)

docs: point to commander's options documentation

---

.changeset/chatty-impalas-sin.md
apps/docs/docs/api.md
apps/docs/docs/features/commander.md
packages/nest-commander/src/command-runner.interface.ts
packages/nest-commander/src/command-runner.service.ts

This adds in some metadata for `@Option()` to make commander use `requiredOption` so that if the option is missing when the command is ran, it fails with an error message. Similar to a missing required argument. 
This commit also updates the implementation to no longer use the `description` methods to add argument descriptions, but maps them manually from the existing metadata to bring no breaking changes. Just making a mention in case things break. Closes #37

feat: add requiredOption for option metadata

---

.changeset/pink-forks-smile.md
.github/workflows/ci.yml
.github/workflows/docs-deploy.yml
.github/workflows/release.yml
apps/docs/docs/api.md
apps/docs/docs/features/commander.md
integration/sub-commands/src/bottom.command.ts
integration/sub-commands/src/mid-1.command.ts
integration/sub-commands/src/mid-2.command.ts
integration/sub-commands/src/nested.module.ts
integration/sub-commands/src/top.command.ts
integration/sub-commands/test/sub-commands.spec.ts
packages/nest-commander/src/command-runner.interface.ts
packages/nest-commander/src/command-runner.service.ts
packages/nest-commander/src/command.decorators.ts
packages/nest-commander/src/constants.ts

This will allow devs to set up sub/nested commands, similar to those from `docker` like `docker compose up` or `docker compose down`. There's a bit of recursive work going on here, so it may get to the point that we want some of this info to be cached, but it's working for now. 
closes #44

feat: allows the ability to create subcommands

---

README.md

This PR updates the link as it is broken leads to a page github with 404.

docs(readme): updates documentations link

---

.github/ISSUE_TEMPLATE/config.yml
apps/docs/docs/api.md
apps/docs/docs/features/factory.md
apps/docs/docs/features/inquirer.md
apps/docs/docs/features/plugins.md
apps/docs/docs/schematics/usage.md
apps/docs/docs/testing/factory.md
packages/nest-commander-schematics/src/question/files/__name@dasherize__.questions.ts.template

I've read the whole docs and template files. Didn't find any other typo.

style: fix misspelled 'parse'; and minor improvements on docs

---

apps/docs/docs/api.md
apps/docs/docs/executing/local.md
apps/docs/docs/features/factory.md

I've tested the behavior when both `transform` and `@TransformFor()` are used (for the same question). The `transform` function on `@Question()` is overwritten by the `@TransformFor()` one. To document this behavior I choose _"(...) This will be overwritten by the `@TransformFor()` counterpart."_. Let me know if this text can be improved.

docs: minor fixes and improvements to api, feature and executing pages

---

.changeset/rotten-candles-dress.md
packages/nest-commander-schematics/package.json
packages/nest-commander-schematics/src/command/schema.json
packages/nest-commander-schematics/src/question/schema.json

As we cannot pass the options when using `nest g -c nest-commander-schematics <schematic>`, I think it would be cool if every option has a prompt.

Minor fix on npm-scripts, and add `x-prompt` on every schematic

---

.changeset/eight-rivers-complain.md
.changeset/thick-cheetahs-hang.md
apps/docs/docs/api.md
apps/docs/docs/features/commander.md
integration/index.spec.ts
integration/option-choices/src/choices-provider.service.ts
integration/option-choices/src/option-choices.command.ts
integration/option-choices/src/option-choices.module.ts
integration/option-choices/test/option-choices.spec.ts
integration/sub-commands/src/mid-2.command.ts
integration/sub-commands/test/sub-commands.spec.ts
package.json
packages/nest-commander/package.json
packages/nest-commander/src/command-runner.interface.ts
packages/nest-commander/src/command-runner.service.ts
packages/nest-commander/src/command.decorators.ts
packages/nest-commander/src/constants.ts
pnpm-lock.yaml

Option choices are now supported either as a static string array
or via the `@OptionChoicesFor()` decorator on a class method.
This decorator method approach allows for using a class's injected
providers to give the chocies, which means they could come from a
database or a config file somewhere if the CLI is set up to handle
such a case
closes #327 #360

feat: allow for option choices and sub command aliases

---

package.json
pnpm-lock.yaml
workspace.json

Changes were made by running `nx migrate latest` and `nx migrate -- --run-migrations`.

chore: update nx to 14

---

apps/docs/docs/features/commander.md

When reading the docs I missed that it was necessary to add subcommands to the CLI module's providers. I see there a couple of other issues opened in the past of others with the same issue so it seemed worth adding some additional details to docs.

chore(docs): Add additional details on subcommands

---

apps/docs/docs/features/commander.md

Hi
I was reading the doc, and while I was copy pasting to get a working base, I encountered those little typos :)
NB: ( not related )
I used your package in a previous project, now it's time to install it on the one I'm starting, this is really usefull
I saw it has already been updated to match nest@9, GGs !!
Have a nice day !

typo(doc): add imports and fix typo in example

---

.changeset/green-spiders-glow.md
.changeset/smart-keys-cheat.md
packages/nest-commander-schematics/src/command/files/with-questions/__name@dasherize__.command.ts.template
packages/nest-commander-schematics/src/command/files/without-questions/__name@dasherize__.command.ts.template
workspace.json

Update the schematic to use the new `extends CommandRunner` from ``nest-commander@3.0.0`
Publish a new patch for nest-commander-testing to include nest-commander 3.0.0 as a peer dep

feat: nest-commander-scheamtics 3.0.0

---

.changeset/wise-buses-smoke.md
packages/nest-commander/src/command-runner.interface.ts
packages/nest-commander/src/command-runner.service.ts

With the `env` option, the option value can come from `process.env`, as this
is already supported by `commander`.
fix: #598

feat: add env property to option decorator

---

.changeset/witty-spiders-cheat.md
packages/nest-commander/src/command.factory.ts

Before this change I am unable to import modules that have been created w/ ESM (`"type": "module"` in their `package.json` and built with ES2015+ as a target), this change will allow this dynamic importing to work for ESM as well as CommonJS modules.

fix: importing of ESM plugins (previously only worked with CommonJS)

---

README.md

The logo in the readme is not displayed (see screenshot):

docs(): update nest-commander logo

---

.changeset/six-geckos-travel.md
apps/docs/src/pages/en/api.md
packages/nest-commander/src/command-factory.interface.ts
packages/nest-commander/src/command-runner.service.ts

Adds a new options to the `CommandFactory.run()` so that the same option in a command and sub-command can be parsed separately. With this option enabled the two commands will be read differently by commander
```
say -m hello yellow
say yellow -m hello
```
The former will have `hello` go to the `say` command while the latter will have `hello` go to the `yellow` sub-command of `say`
Closes #663

feat: allow for positional options

---

.changeset/popular-dodos-trade.md
apps/docs/src/pages/en/api.md
apps/docs/src/pages/en/features/commander.md
apps/docs/src/pages/en/features/factory.md
apps/docs/src/pages/en/features/inquirer.md
integration/index.spec.ts
integration/register-provider/src/bottom.command.ts
integration/register-provider/src/mid-1.command.ts
integration/register-provider/src/mid-2.command.ts
integration/register-provider/src/nested.module.ts
integration/register-provider/src/top.command.ts
integration/register-provider/test/register-with-subcommands.spec.ts
packages/nest-commander/src/command-runner.interface.ts

Close https://github.com/jmcdo29/nest-commander/issues/705.
I also add two sections named with Command Runner and Regsitere Commands to your docs and fix links broken I found in https://github.com/jmcdo29/nest-commander/pull/706/commits/4a3dd2d3e553539e62aeecf6d89cd5855e9f0d19.

RegisterCommands method

---

.changeset/dry-months-return.md
apps/docs/src/pages/en/features/commander.md
integration/default-sub-commands/src/bottom.command.ts
integration/default-sub-commands/src/mid-1.command.ts
integration/default-sub-commands/src/mid-2.command.ts
integration/default-sub-commands/src/nested.module.ts
integration/default-sub-commands/src/top.command.ts
integration/default-sub-commands/test/default-sub-commands.spec.ts
integration/index.spec.ts
packages/nest-commander/src/command-runner.service.ts

By adding `options: { isDefault: true }` to a `@SubCommand()` the sub command will be considered the default sub command and activated if `<command>` is called without any extra subcommands
Ref #663

feat: allow for a sub command to be the default

---

.changeset/gentle-lemons-explain.md
packages/nest-commander-testing/src/command-test.factory.ts

Hello,
i would like to use the `runWithoutClosing` method for e2e test too.
My cronjob creates a report in the database. After the command ran, i would like to query the database and check the result. 
This is not possible with the `run` method. The application closes.
With `runWithoutClosing` i can query the databse, check the result and close the application after the ckeck.
Example: 
```ts
// imports ...
describe("Cronjob User Count (e2e)", () => {
let commandInstance: TestingModule;
let usersRepository: UsersRepository;
let usersReportsRepository: UsersReportsRepository;
beforeEach(async () => {
commandInstance = await CommandTestFactory.createTestingCommand({
imports: [AppModule],
}).compile();
usersRepository = commandInstance.get(UsersRepository);
usersReportsRepository = …
```

feat: runWithoutClosing for testing

---

.changeset/chilled-jars-smile.md
apps/docs/src/pages/en/api.md
apps/docs/src/pages/en/features/commander.md
integration/index.spec.ts
integration/request-provider-override/src/request-provider.module.ts
integration/request-provider-override/src/request-scoped.service.ts
integration/request-provider-override/src/simple.command.ts
integration/request-provider-override/test/index.spec.ts
packages/nest-commander/src/command-runner.module.ts
packages/nest-commander/src/command-runner.service.ts
packages/nest-commander/src/index.ts
packages/nest-commander/src/request-module.decorator.ts

The addition of the `@RequestModule()` decorator allows for users to
override the standard `REQUEST` object that Nest provides. This is so
users can use request scoped providers without having to re-architect
their entire application and instead can just provide a mock object.
ref: #754

feat(core): add new module decorator to set request

---

.changeset/forty-rockets-beg.md
apps/docs/src/pages/en/api.md
packages/nest-commander/src/command-factory.interface.ts
packages/nest-commander/src/command-runner.service.ts

This option varies from the `errrorHandler` option in that it catches
errors at the Nest execution level so that the `onApplicationShutdown`
hook (and similar) can still function properly
ref #794

feat: add in a service error handler option

---

apps/docs/src/pages/en/features/plugins.md

There were some typos, when I read features/plugin docs.

docs(plugins): correct typos

---

apps/docs/src/pages/en/execution.md

Update `execution.md` to show `nest start` now appears to pass arguments to the program after `--`.

Update to show passing arguments to `nest start`

---

apps/docs/src/pages/en/execution.md

Following the last option for CLI execution described on [this page](https://nest-commander.jaymcdoniel.dev/en/execution/#packaging-the-cli), I encountered a few problems whose origin is the documentation, which is fixed in this PR.
The problems:
- From `dist/main` to `dist/main.js` when setting up the bin field of `package.json` (otherwise there's no bin symlinked during npm install)
- Add a missing `#!/usr/bin/env node` shebang in `main.ts` (otherwise bin isn't executed with the node runtime)
This PR also specifies better where the bin is installed in the context of global installations.

Update CLI publication doc

---

.changeset/tidy-poets-turn.md
integration/index.spec.ts
integration/output-config/src/basic.command.ts
integration/output-config/src/root.module.ts
integration/output-config/test/output.config.spec.ts
packages/nest-commander-testing/src/command-test.factory.ts
packages/nest-commander/src/command-factory.interface.ts
packages/nest-commander/src/command-runner.service.ts
packages/nest-commander/src/command.factory.ts
packages/nest-commander/src/index.ts

Hey ! 
I have been using nest-commander for a project and needed to override the commander error response (unknown command, options error, etc.) to use my logger instead. However, it seems that nest-commander does not provide an interface that allows access to the outputConfiguration.
Therefore, I attempted to bypass the interface by doing the following:
```ts
async function bootstrap() {
const app = await CommandFactory.createWithoutRunning(CommandsModule, {
logger: new Logger(),
});
/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable n/handle-callback-err */
const m = app.get(CommandRunnerService);
// @ts-expect-error
const cmd = m.commander as Command; // force to get a private property
cmd.configureOutput({
writeErr: (str: string): void => {
console.error(str);
}, …
```

Feat add output configuration

---

.changeset/polite-socks-develop.md
apps/docs/src/pages/en/api.md
integration/index.spec.ts
integration/version-option/src/root.module.ts
integration/version-option/test/version.option.spec.ts
packages/nest-commander/src/command-factory.interface.ts
packages/nest-commander/src/command-runner.service.ts

Hey again @jmcdo29  ;) !
I made a really small change. I wanted to include the current version of my API in a cli option.
So I added the version option at the factory level :
```ts
const app = await CommandFactory.createWithoutRunning(CommandsModule, {
version: getVersion() ?? 'UNKNOWN'
});
```
Do you think it deserves to be merged?
Thank

Add global version option

---

.changeset/happy-rules-work.md
packages/nest-commander/src/command-runner.service.ts

Due to the need to call the custom error handler when it is passed
it makes more sense to generally just re-throw the existing error
if one occurs. So now, there will be a logged message about possibly
using a request scoped service and the error will be fully handled
by the error handler.
ref: #1039

fix: re-throw error regardless if it is a reading undefined error

---

.changeset/kind-turkeys-type.md
integration/option-choices/src/option-choices.command.ts
integration/option-choices/test/option-choices.spec.ts
packages/nest-commander/src/command-runner.service.ts

There was already a test for this, that I didn't realize was initially incorrect, so I was able to verify this does indeed work as expected
fix: #1070

fix: use the name passed to the options decorator for the name passed to the command

---

apps/docs/src/pages/en/execution.md

docs(execution): fix 'kick off' typo

---

apps/docs/src/pages/en/features/commander.md

docs(features/commander): fix 'interfere' typo

---

.changeset/ten-rivers-fold.md
packages/nest-commander/src/constants.ts

This pull request includes changes to the `packages/nest-commander/src/constants.ts` file. The changes introduce a new feature to the `_{{app_name}}_nest_commander_completions()` function that allows filename completion when the last word starts with common filesystem operator characters such as `.`, `/`, or `~`. This feature is enabled when the `{{app_name}}_nest_commander_filesystem_completions` variable is set to "true" or "1". Additionally, a fallback to filename completion has been added for zsh when no match is found.
Here are the key changes:
* [`packages/nest-commander/src/constants.ts`](diffhunk://#diff-830f743ddff716c79c2812e2da71412bd098f7afff83589c05012db0db72fc54R49-R58): Added a condition to check if `{{app_name}}_nest_commander_filesystem_completions` is set to "true" or …

feat: add optional support for filesystem autocompletion

---

apps/docs/src/pages/en/schematics/usage.md

Fix typo: "fale" to "false"

---

.changeset/twelve-rabbits-nail.md
packages/nest-commander/src/command-factory.interface.ts
packages/nest-commander/src/command-runner.service.ts
packages/nest-commander/src/command.factory.ts

Add option for Help Configuration using the `.configureHelp()` function in commander js
https://github.com/tj/commander.js/tree/v11.1.0?tab=readme-ov-file#more-configuration-2

Add option for Help Configuration

---

package.json
pnpm-lock.yaml

Follow-up on #1216, I forgot to bump `@nestjs/core` in the dependencies.
No need for changeset as this only impact the dev environment.

chore: upgrade to @nestjs/core to v11

---

.changeset/soft-geckos-know.md
apps/docs/src/pages/en/api.md
packages/nest-commander/src/command.factory.ts

`CommandFactory.run()` already supports running dynamic modules, but the type `Type<any>` doesn't allow passing `DynamicModule`.

fix: support dynamic modules in `CommandFactory`

---

packages/nest-commander/src/command.factory.ts

When calling `CommandFactory.run()`, ensure that the app is closed by wrapping it in a try/finally clause.

Ensure app is closed using try/finally

---

apps/docs/src/pages/en/features/inquirer.md

This pull request includes a small change to the `apps/docs/src/pages/en/features/inquirer.md` file. The change corrects the link to the API documentation for the `InquirerService`'s `ask` command.
Documentation update:
* [`apps/docs/src/pages/en/features/inquirer.md`](diffhunk://#diff-688de577abd7fdeb941fb1dd7244c34a78eeba8caad62eddedcd1137a8dd7b31L116-R116): Corrected the link to the API documentation from `../api` to `../api.md`.

Update api reference link from '../api' to '../api.md'

---

.changeset/friendly-ears-scream.md
packages/nest-commander/package.json
pnpm-lock.yaml

This PR resolves #1239.
#1240 updated it in the root package dev dependencies but did not update the version in the actual package that is published.

chore: upgrade @golevelup/nestjs-discovery from 4.0.3 to 5.0.0

---

.changeset/five-comics-add.md
packages/nest-commander-testing/package.json
packages/nest-commander/package.json

Fixed typo in the relative path to packages in the repository.
Not urgent, so I'm not sure if this warrants an actual bump of versions.

fix: set correct relative path to packages in repository
